distributionUrl=https://archive.apache.org/dist/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip
distributionSha256Sum=2a5df1c9d027948a019952c0b3c003c33c1e50ef22a22b7d170ed473e310f679
wrapperUrl=https://repo1.maven.org/maven2/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.jar
